---

- name: Base rhel8 install
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
  - name: Install specific packages
    dnf:
      name:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        - emacs-nox
        - git-core
        - procps-ng
        - tmux

  - name: Update all packages
    dnf:
      name: "*"
      state: latest

  - name: Set authorized keys taken from url
    authorized_key:
      user: cloud_user
      state: present
      key: https://github.com/SebastianThorn.keys

  - name: Remove need for password for cloud_user
    lineinfile:
      path: /etc/sudoers.d/90-cloud-init-users
      regexp: '^cloud_user'
      line: cloud_user ALL=(ALL) NOPASSWD:ALL